---
title: "Untitled"
author: "Sina Mokhtar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
# load library
library(dplyr)
library(stringr)
library(ggplot2)
library(readxl)
```



### load the dataset
```{r}
filename = "UT Comp_Seq.xlsx"
conocoPhillips = read_excel(filename) %>%
    rename(comType = "Compl. Type" ,
           cumProd = "12 month Cum Prod")
names(conocoPhillips)
summary(conocoPhillips)
com_na = conocoPhillips %>%
    filter(is.na(`Compl. Type`))
hist(com_na$`12 month Cum Prod`)

ggplot(data = conocoPhillips,
       aes(x = as.factor(comType),
           y = cumProd)) +
    geom_boxplot()

table(conocoPhillips$comType)
length(unique(conocoPhillips$comType))
conocoPhillips1 = conocoPhillips %>%
    mutate(comType = tolower(comType),
           comType = str_trim(comType),
           comType = str_squish(comType),
           comType = gsub("sleeves",
                          "sleeve",
                          comType),
           comType = gsub("and",
                          "&",
                          comType),
           comType = gsub("p & p",
                          "p&p",
                          comType)) %>%
    group_by(comType) %>%
    summarise(count = n(),
              cumProd_total = sum(cumProd))

length(unique(conocoPhillips1$comType))  
sort(unique(conocoPhillips1$comType))
```

